### ISSUE TITLE
ValidationErrors when trying to generate client from Candy Machine IDL

### ISSUE THREAD

**Issue by cdb18** [kevinheavey/anchorpy#86]
From this IDL json: https://gist.github.com/cdb18/43cff60234a9e2a02949347f11c91240

```anchorpy client-gen --program-id cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ /Users/yexiongf/code/metaplex-program-library/target/idl/candy_machine.json .
Traceback (most recent call last):
  File "/opt/homebrew/bin/anchorpy", line 8, in <module>
    sys.exit(app())
  File "/opt/homebrew/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/homebrew/lib/python3.9/site-packages/anchorpy/cli.py", line 110, in client_gen
    idl_obj = Idl.from_json(idl_dict)
  File "/opt/homebrew/lib/python3.9/site-packages/anchorpy/idl.py", line 272, in from_json
    return deserialize(cls, idl)
  File "/opt/homebrew/lib/python3.9/site-packages/apischema/utils.py", line 400, in wrapper
    return wrapped(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/apischema/deserialization/__init__.py", line 891, in deserialize
    return deserialization_method(
  File "apischema/deserialization/methods.pyx", line 494, in apischema.deserialization.methods.ObjectMethod.deserialize
  File "apischema/deserialization/methods.pyx", line 495, in apischema.deserialization.methods.ObjectMethod.deserialize
  File "apischema/deserialization/methods.pyx", line 1078, in apischema.deserialization.methods.ObjectMethod_deserialize
apischema.validation.errors.ValidationError: ValidationError: [{'loc': ['accounts', 0, 'docs'], 'err': 'unexpected property'}, {'loc': ['accounts', 1, 'docs'], 'err': 'unexpected property'}, {'loc': ['instructions', 6, 'accounts', 13, 'accounts'], 'err': 'missing property'}, {'loc': ['instructions', 6, 'accounts', 13, 'docs'], 'err': 'unexpected property'}, {'loc': ['instructions', 6, 'accounts', 13, 'docs'], 'err': 'unexpected property'}, {'loc': ['instructions', 6, 'accounts', 13, 'isMut'], 'err': 'unexpected property'}, {'loc': ['instructions', 6, 'accounts', 13, 'isSigner'], 'err': 'unexpected property'}, {'loc': ['types', 0, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 0, 'type', 'fields'], 'err': 'unexpected property'}, {'loc': ['types', 0, 'type', 'fields', 2, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 0, 'type', 'fields', 3, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 0, 'type', 'fields', 13, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 0, 'type', 'kind'], 'err': "not one of ['enum'] (oneOf)"}, {'loc': ['types', 0, 'type', 'variants'], 'err': 'missing property'}, {'loc': ['types', 1, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 1, 'type', 'fields'], 'err': 'unexpected property'}, {'loc': ['types', 1, 'type', 'fields', 1, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 1, 'type', 'kind'], 'err': "not one of ['enum'] (oneOf)"}, {'loc': ['types', 1, 'type', 'variants'], 'err': 'missing property'}, {'loc': ['types', 4, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 6, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 6, 'type', 'fields'], 'err': 'unexpected property'}, {'loc': ['types', 6, 'type', 'fields', 0, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 6, 'type', 'fields', 1, 'docs'], 'err': 'unexpected property'}, {'loc': ['types', 6, 'type', 'kind'], 'err': "not one of ['enum'] (oneOf)"}, {'loc': ['types', 6, 'type', 'variants'], 'err': 'missing property'}]
```

**Comment by kevinheavey** [comment]
Closed by #88
