### ISSUE TITLE
Error while decoding to utf-8

### ISSUE THREAD

**Issue by aleixisp** [kevinheavey/anchorpy#89]
Hey, 
I'm running into this error, not sure what's going wrong.
Quite new using anchorpy, let me know if I can provide with any extra info, trying to figure it out in my side too!.

```bash
(<class 'UnicodeDecodeError'>, UnicodeDecodeError('utf-8', b'\x02F\xca@\xb2E#\xa3Y>\xa7\xe8\xe8\xbe\xb3\xebu%\x9ak\x9a\xa3\x98\xb7\xe9\xec\x01NI\xa1\x19\xb3O\xfb%\x90n;d[\x8d\xb5\x83J\xf5\xac\x16B\xce\xa4\x10\xf9VY\xc6v\xb3\x1d5\x88\x04\xa4\xf42\x0e&\x0e\x98o"\xe2\xafz\xb1\x8e-3\xc7\x89#\xa6\xe4u\x17\x7f\xdb\xe38\x0f)\x8e\xae\x9c\xb2\xe7\x9a&Q\xc4\xcf\xe1\x9au\xf2\xbf6\xf1\x06\xa4]\xc4E\xe8X!\xe3\xea\xf2\x1b+jL\x9aJ\xb7\x17\x107\t\x02\x00\x02\x04j&\x7f\x8a\xa8|\n\x8a\x83\xe0\x90\xb1\xd5\xc1\xca\xb0!qYZL\xf6\xc5C:\x03\x1a\xb1\x88\xe2\xda\xd5]D\x88\x7fB\n6v\x81\xaa\xfe\x14V@^h\x99\xdf\xec\xef\xc6ZiY\xf1\x82x\xfe\x82\x9bF\x81\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\xa54\x985w\xd8\xa7\x01\xf7\xc9\xef\xb1\xcd\xbc!\xc7\x97\xce\x02\'\xba\xb6\x02AX\xf8\x0b\x1bz\xec\xbb\x9e\x11\xc4\xf7!\xa0G\xcbY\x99C\xdb\xdd\x91|\x00\x7fGXCW\xc6@\x16xo&\xc0>u\xdf\x92!\x01\x03\x04\x00\x00\x01\x02\x7fz\x00\x00\x00localhost:5001/v1_1_0/assets/37570e1b-a121-4e3a-83f2-dd7525ac4d89/web3/solana/7H5XZos2ScDSYKCpvdKe9vpamP8wXYnDZoAJrwNzqZNG\x00', 2, 3, 'invalid continuation byte'), <traceback object at 0x7fe82699d940>)
[2022-08-18 19:24:02,209] ERROR in http: Traceback (most recent call last):
  File "app/errors.py", line 52, in wrapper
    return f(*args, **kwargs)
  File "/app/utils/blueprints.py", line 73, in wrapper
    return fn(*args, **kwargs)
  File "/web3/routes.py", line 24, in tokenize_asset_on_chain_route
    token = tokenize_asset_on_chain_service(asset_id, transaction_id, data)
  File "/web3/services.py", line 138, in tokenize_asset_on_chain_service
    response = send_solana_transaction_to_chain(transaction_model)
  File "/web3/olyn_solana/service.py", line 65, in send_solana_transaction_to_chain
    print(client.simulate_transaction(txn.serialize(), sig_verify=True))
  File "/lib/python3.9/site-packages/solana/rpc/api.py", line 1421, in simulate_transaction
    args = self._simulate_transaction_args(txn, sig_verify, commitment)
  File "/lib/python3.9/site-packages/solana/rpc/core.py", line 433, in _simulate_transaction_args
    wire_format = txn.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 2: invalid continuation byte
```

Regards,
Aleix

**Comment by kevinheavey** [comment]
Could you provide a reproducible example?

**Comment by aleixisp** [comment]
Let me try:

To reproduce the current one:
```python
s_msg = "020002046a267f8aa87c0a8a83e090b1d5c1cab02171595a4cf6c5433a031ab188e2dad5a6d401f4653d5b8758540346f01d4819d126eef5d0f0cd749475080a7fba4ffe0000000000000000000000000000000000000000000000000000000000000001a534983577d8a701f7c9efb1cdbc21c797ce0227bab6024158f80b1b7aecbb9e0b06ced45cbf1d571d87bbc2bbe810378b54a70859933d1e468232ccf5207989010304000001027f7a0000006c6f63616c686f73743a353030312f76315f315f302f6173736574732f30616366623936622d323533342d343866352d396630392d3562323932616264333561362f776562332f736f6c616e612f434545424d4b744c69623852754b6563664450554e696832767732464c656852475166646564664344686a4200"
owner_p_k = "89NGK1ZaE1KyVeaLwajLcreSNJjAkCDo4gwGZrHuWP48"
owner_p_k_signature_hex = "095918667ee60db6833105d68c3b2b4bb050c7c775d51fe9c01d2fa7ac754dac1a4d7ac5fa6aa6892c495b1cd15f756140ed3cc72b8fb585dc76e99ba24bf007"
token_p_k = "CEEBMKtLib8RuKecfDPUNih2vw2FLehRGQfdedfCDhjB"
token_p_k_signature_hex =  "da3858238c9e6e7a3cf17d870e3723ccc4ff7cee16882a1a23596b358edf76091beab5ad7055f621f6443ef55f9e6a4839f4f78e2284a332da052484f79c8206"

transaction_model: Transaction = Transaction.populate(
        message=Message.deserialize(s_msg),
        signatures=[Signature(owner_p_k_signature_hex), Signature(bytes.fromhex(token_p_k_signature_hex))]
    )

```

Hope this works!

**Comment by kevinheavey** [comment]
@aleixisp this part gives me an (expected) error:
```Message.deserialize(s_msg),```

```, line 164, in deserialize
    msg = SoldersMessage.from_bytes(raw_message)
TypeError: argument 'data': 'str' object cannot be converted to 'PyBytes'```

This is because the argument to `Message.deserialize` needs to be bytes

**Comment by aleixisp** [comment]
hello ,my bad.
Missed a line here. In my code i'm converting the hex message to bytes. My mistake

```python
hex_msg = "020002046a267f8aa87c0a8a83e090b1d5c1cab02171595a4cf6c5433a031ab188e2dad5a6d401f4653d5b8758540346f01d4819d126eef5d0f0cd749475080a7fba4ffe0000000000000000000000000000000000000000000000000000000000000001a534983577d8a701f7c9efb1cdbc21c797ce0227bab6024158f80b1b7aecbb9e0b06ced45cbf1d571d87bbc2bbe810378b54a70859933d1e468232ccf5207989010304000001027f7a0000006c6f63616c686f73743a353030312f76315f315f302f6173736574732f30616366623936622d323533342d343866352d396630392d3562323932616264333561362f776562332f736f6c616e612f434545424d4b744c69623852754b6563664450554e696832767732464c656852475166646564664344686a4200"
s_msg: bytes = bytes.fromhex(hex_msg)
transaction_model: Transaction = Transaction.populate(
        message=Message.deserialize(s_msg),
        signatures=[Signature(owner_p_k_signature_hex), Signature(bytes.fromhex(token_p_k_signature_hex))]
    )
```

**Comment by kevinheavey** [comment]
@aleixisp if you want to pass bytes to `.simulate_transaction` then you need to do `client.simulate_transaction(b64encode(txn.serialize()).decode("utf-8"))`.

Or you could just to `client.simulate_transaction(txn)`

**Comment by kevinheavey** [comment]
This works (well it gets BlockhashNotFound but that's expected since the message is old):
```python
from solana.transaction import Transaction
from solders.signature import Signature
from solana.message import Message
from solana.rpc.api import Client as SolanaClient
owner_p_k_signature_hex = "095918667ee60db6833105d68c3b2b4bb050c7c775d51fe9c01d2fa7ac754dac1a4d7ac5fa6aa6892c495b1cd15f756140ed3cc72b8fb585dc76e99ba24bf007"
token_p_k_signature_hex =  "da3858238c9e6e7a3cf17d870e3723ccc4ff7cee16882a1a23596b358edf76091beab5ad7055f621f6443ef55f9e6a4839f4f78e2284a332da052484f79c8206"
hex_msg = "020002046a267f8aa87c0a8a83e090b1d5c1cab02171595a4cf6c5433a031ab188e2dad5a6d401f4653d5b8758540346f01d4819d126eef5d0f0cd749475080a7fba4ffe0000000000000000000000000000000000000000000000000000000000000001a534983577d8a701f7c9efb1cdbc21c797ce0227bab6024158f80b1b7aecbb9e0b06ced45cbf1d571d87bbc2bbe810378b54a70859933d1e468232ccf5207989010304000001027f7a0000006c6f63616c686f73743a353030312f76315f315f302f6173736574732f30616366623936622d323533342d343866352d396630392d3562323932616264333561362f776562332f736f6c616e612f434545424d4b744c69623852754b6563664450554e696832767732464c656852475166646564664344686a4200"
s_msg: bytes = bytes.fromhex(hex_msg)
txn = Transaction.populate(
        message=Message.deserialize(s_msg),
        signatures=[Signature(bytes.fromhex(owner_p_k_signature_hex)), Signature(bytes.fromhex(token_p_k_signature_hex))]
    )
client = SolanaClient(endpoint="https://api.devnet.solana.com")
print(client.simulate_transaction(txn, sig_verify=True))```

**Comment by aleixisp** [comment]
Unfortunately no, the example had an old Blockhash, which lead to fail upon that verification. With an up to date blockhash.
If I try to send the txn rather to simulated it first, i get this error.
```python
solana.rpc.core.RPCException: {'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc0', 'data': {'accounts': None, 'err': {'InstructionError': [0, {'Custom': 3008}]}, 'logs': ['Program C7tnXr2GaGkvaqvANAvcT2NX2DdmaNXa3tHMrwqpjUUu invoke [1]', 'Program log: Instruction: NftCreateV1', 'Program log: AnchorError caused by account: system_program. Error Code: InvalidProgramId. Error Number: 3008. Error Message: Program ID was not as expected.', 'Program log: Left:', 'Program log: 11111111111111111111111111111112', 'Program log: Right:', 'Program log: 11111111111111111111111111111111', 'Program C7tnXr2GaGkvaqvANAvcT2NX2DdmaNXa3tHMrwqpjUUu consumed 5728 of 200000 compute units', 'Program C7tnXr2GaGkvaqvANAvcT2NX2DdmaNXa3tHMrwqpjUUu failed: custom program error: 0xbc0'], 'unitsConsumed': 0}}
```

There is something wrong with how the programID is being passed, I'm exploring that.

**Comment by aleixisp** [comment]
fixed it!

Dummy issue, although not sure if i entirely wrote that part.
the error is located ehre:
```python
ix: TransactionInstruction = nft_create_v1(
        args=ix_args,
        accounts=NftCreateV1Accounts(
            authority=owner_pubkey,
            holder=owner_pubkey,
            nft=token_keypair.public_key,
            system_program=PublicKey(1)  # System program
        ),
        program_id=PROGRAM_ID
    )
```

Where `system_program` PubKey was wrongly generated!

This solved my issues!
```python
system_program=PublicKey("11111111111111111111111111111111")  # System program
```
